version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.6.4
    working_directory: /tmp/workspace

jobs:
  build:
    executor: docker-executor
    working_directory: /tmp/workspace/farmsmart
    steps:
      - checkout
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - farmsmart
  validate:
    executor: docker-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: "validate schema"
          command: |
            sudo pip install json-spec
            echo "Validate Crop"
            json validate --schema-file=farmsmart/schemas/crop.schema.json --document-file=farmsmart/json/crop.sample.json
            echo "Validate crop Stage"
            json validate --schema-file=farmsmart/schemas/cropStage.schema.json --document-file=farmsmart/json/crop_stage.sample.json
            echo "Validate crop Article"
            json validate --schema-file=farmsmart/schemas/article.schema.json --document-file=farmsmart/json/article.sample.json
            echo "Validate crop Article Directory"
            json validate --schema-file=farmsmart/schemas/articleDirectory.schema.json --document-file=farmsmart/json/articleDirectory.sample.json

workflows:
  version: 2
  backend:
    jobs:
      - build
      - validate:
          requires:
            - build
